"""empty message

Revision ID: 687e359f076c
Revises: 8b24ea154580
Create Date: 2019-04-26 15:19:52.954845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '687e359f076c'
down_revision = '8b24ea154580'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conferences', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['enddate'])
        batch_op.create_unique_constraint(None, ['startdate'])
        batch_op.drop_column('end_date')
        batch_op.drop_column('start_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conferences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_date', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('end_date', sa.DATETIME(), nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
