"""empty message

Revision ID: 8b24ea154580
Revises: e059460be4c3
Create Date: 2019-04-26 14:59:08.559421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b24ea154580'
down_revision = 'e059460be4c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conferences', sa.Column('enddate', sa.DateTime(), nullable=True))
    op.add_column('conferences', sa.Column('startdate', sa.DateTime(), nullable=True))
    op.create_unique_constraint(None, 'conferences', ['enddate'])
    op.create_unique_constraint(None, 'conferences', ['startdate'])
    op.drop_column('conferences', 'start_date')
    op.drop_column('conferences', 'end_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conferences', sa.Column('end_date', sa.DATETIME(), nullable=True))
    op.add_column('conferences', sa.Column('start_date', sa.DATETIME(), nullable=True))
    op.drop_constraint(None, 'conferences', type_='unique')
    op.drop_constraint(None, 'conferences', type_='unique')
    op.drop_column('conferences', 'startdate')
    op.drop_column('conferences', 'enddate')
    # ### end Alembic commands ###
